SPECIAL>NOINTERACTION
SPECIAL>LOADMODEL|EPS-tf.mdl

SIMULATE>RUNNAME|BAU
MENU>RUN|o

SIMULATE>RUNNAME|Expert
SIMULATE>READCIN|Expert.cin
MENU>RUN|o

SIMULATE>RUNNAME|Ruling
SIMULATE>READCIN|Ruling.cin
MENU>RUN|o

SIMULATE>RUNNAME|Opposition
SIMULATE>READCIN|Opposition.cin
MENU>RUN|o

SIMULATE>RUNNAME|Raising
SIMULATE>READCIN|Raising.cin
MENU>RUN|o

MENU>EXIT
